language: python
python:
  - "2.7"
  - "3.3"
install:
  - pip install -r requirements.txt --use-mirrors
  - python setup.py install
  # convert in case of py3k only:
  - if [[ $(echo $TRAVIS_PYTHON_VERSION | awk -F. '{ print $1 }') -gt 2 ]]; then 2to3 -w build; fi
before_script:
  - pwd
  - ls -laht
  - pip install -U -r test_requirements.txt --use-mirrors
  - if [[ $(echo $TRAVIS_PYTHON_VERSION | awk -F. '{ print $1 }') -gt 2 ]]; then 2to3 -w rtkit; fi
  - rm -rf __pycache__ && rm -rf */__pycache__ && rm -rf */*/__pycache__
  #- 2to3 -w build
script:
  - python setup.py test
    #  - py.test --doctest-modules --pep8 rtkit -v --cov rtkit --cov-report term-missing
after_success:
  - pip install python-coveralls --use-mirrors
  - coveralls
